
package MP3PlayerPackage;
import java.awt.Color;
import java.awt.geom.RoundRectangle2D;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;


public class MP3PlayerGUII extends javax.swing.JFrame {

    /**
     * Creates new form MP3PlayerGUII
     */
    Controlers co=new Controlers();
    int xMouse,yMouse;
    public MP3PlayerGUII() {
        initComponents();
        this.setShape(new RoundRectangle2D.Double(0,0,getWidth(),getHeight(),20,20));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        minBtn = new javax.swing.JLabel();
        closeBtn = new javax.swing.JLabel();
        dragBar = new javax.swing.JLabel();
        playBtn = new javax.swing.JLabel();
        stopBtn = new javax.swing.JLabel();
        pauseBtn = new javax.swing.JLabel();
        openBtn = new javax.swing.JLabel();
        loopBtn = new javax.swing.JLabel();
        songTitleR = new javax.swing.JLabel();
        songTitle = new javax.swing.JLabel();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minBtn.setFont(new java.awt.Font("saxMono", 1, 14)); // NOI18N
        minBtn.setForeground(new java.awt.Color(255, 255, 255));
        minBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minBtn.setText("-");
        minBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minBtnMouseExited(evt);
            }
        });
        getContentPane().add(minBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 25, 25));

        closeBtn.setFont(new java.awt.Font("saxMono", 1, 12)); // NOI18N
        closeBtn.setForeground(new java.awt.Color(255, 255, 255));
        closeBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeBtn.setText("X");
        closeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeBtnMouseExited(evt);
            }
        });
        getContentPane().add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 25, 25));

        dragBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dragBarMouseDragged(evt);
            }
        });
        dragBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dragBarMousePressed(evt);
            }
        });
        getContentPane().add(dragBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 20));

        playBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MP3PlayerPackage/play_hover1.png"))); // NOI18N
        playBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        playBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                playBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                playBtnMouseExited(evt);
            }
        });
        getContentPane().add(playBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 128, 128));

        stopBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stopBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MP3PlayerPackage/stop_hover1.png"))); // NOI18N
        stopBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        stopBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stopBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stopBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                stopBtnMouseExited(evt);
            }
        });
        getContentPane().add(stopBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 64, 64));

        pauseBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pauseBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MP3PlayerPackage/pause_hover1.png"))); // NOI18N
        pauseBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pauseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pauseBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pauseBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pauseBtnMouseExited(evt);
            }
        });
        getContentPane().add(pauseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 64, 64));

        openBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MP3PlayerPackage/add_hover1.png"))); // NOI18N
        openBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        openBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                openBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                openBtnMouseExited(evt);
            }
        });
        getContentPane().add(openBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 64, 64));

        loopBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loopBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MP3PlayerPackage/loop_hover1.png"))); // NOI18N
        loopBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loopBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loopBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loopBtnMouseExited(evt);
            }
        });
        getContentPane().add(loopBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 64, 64));

        songTitleR.setFont(new java.awt.Font("saxMono", 0, 14)); // NOI18N
        songTitleR.setForeground(new java.awt.Color(255, 255, 255));
        songTitleR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(songTitleR, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 28, 370, 30));

        songTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        songTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MP3PlayerPackage/songTitle.png"))); // NOI18N
        getContentPane().add(songTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 23, 370, 40));

        back.setBackground(new java.awt.Color(255, 102, 0));
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setOpaque(true);
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 200));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dragBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragBarMouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
        
    }//GEN-LAST:event_dragBarMouseDragged

    private void dragBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragBarMousePressed
       xMouse=evt.getX();
       yMouse=evt.getY();
        
    }//GEN-LAST:event_dragBarMousePressed

    private void closeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseEntered
        closeBtn.setOpaque(true);
        closeBtn.setBackground(Color.WHITE);
        closeBtn.setForeground(new Color(255,153,51));
    }//GEN-LAST:event_closeBtnMouseEntered

    private void closeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseExited
         closeBtn.setOpaque(false);
        closeBtn.setForeground(Color.WHITE);
    }//GEN-LAST:event_closeBtnMouseExited

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeBtnMouseClicked

    private void minBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minBtnMouseEntered
        minBtn.setOpaque(true);
        minBtn.setBackground(Color.WHITE);
        minBtn.setForeground(new Color(255,153,51));
    }//GEN-LAST:event_minBtnMouseEntered

    private void minBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minBtnMouseExited
        minBtn.setOpaque(false);
        minBtn.setForeground(Color.WHITE);
    }//GEN-LAST:event_minBtnMouseExited

    private void minBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minBtnMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minBtnMouseClicked

    private void playBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playBtnMouseEntered
        // TODO add your handling code here:
        playBtn.setIcon(new ImageIcon("C:\\Users\\abdelkarim\\Documents\\NetBeansProjects\\MP3Player\\src\\MP3PlayerPackage\\play_hover2.png"));
    }//GEN-LAST:event_playBtnMouseEntered

    private void playBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playBtnMouseExited
        playBtn.setIcon(new ImageIcon("C:\\Users\\abdelkarim\\Documents\\NetBeansProjects\\MP3Player\\src\\MP3PlayerPackage\\play_hover1.png"));
    }//GEN-LAST:event_playBtnMouseExited

    private void stopBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stopBtnMouseEntered
        stopBtn.setIcon(new ImageIcon("C:\\Users\\abdelkarim\\Documents\\NetBeansProjects\\MP3Player\\src\\MP3PlayerPackage\\stop_hover2.png"));
   
    }//GEN-LAST:event_stopBtnMouseEntered

    private void stopBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stopBtnMouseExited
        stopBtn.setIcon(new ImageIcon("C:\\Users\\abdelkarim\\Documents\\NetBeansProjects\\MP3Player\\src\\MP3PlayerPackage\\stop_hover1.png"));
   
    }//GEN-LAST:event_stopBtnMouseExited

    private void openBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openBtnMouseEntered
       openBtn.setIcon(new ImageIcon("C:\\Users\\abdelkarim\\Documents\\NetBeansProjects\\MP3Player\\src\\MP3PlayerPackage\\add_hover2.png"));
   
    }//GEN-LAST:event_openBtnMouseEntered

    private void openBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openBtnMouseExited
        // TODO add your handling code here:
        openBtn.setIcon(new ImageIcon("C:\\Users\\abdelkarim\\Documents\\NetBeansProjects\\MP3Player\\src\\MP3PlayerPackage\\add_hover1.png"));
    }//GEN-LAST:event_openBtnMouseExited

    private void pauseBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pauseBtnMouseClicked
        co.pause();
    }//GEN-LAST:event_pauseBtnMouseClicked

    private void pauseBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pauseBtnMouseEntered
        pauseBtn.setIcon(new ImageIcon("C:\\Users\\abdelkarim\\Documents\\NetBeansProjects\\MP3Player\\src\\MP3PlayerPackage\\pause_hover2.png"));
    }//GEN-LAST:event_pauseBtnMouseEntered

    private void pauseBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pauseBtnMouseExited
        // TODO add your handling code here:
        pauseBtn.setIcon(new ImageIcon("C:\\Users\\abdelkarim\\Documents\\NetBeansProjects\\MP3Player\\src\\MP3PlayerPackage\\pause_hover1.png"));
   
    }//GEN-LAST:event_pauseBtnMouseExited

    private void loopBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loopBtnMouseEntered
        // TODO add your handling code here:
        loopBtn.setIcon(new ImageIcon("C:\\Users\\abdelkarim\\Documents\\NetBeansProjects\\MP3Player\\src\\MP3PlayerPackage\\loop_hover2.png"));
   
    }//GEN-LAST:event_loopBtnMouseEntered

    private void loopBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loopBtnMouseExited
        // TODO add your handling code here:
        loopBtn.setIcon(new ImageIcon("C:\\Users\\abdelkarim\\Documents\\NetBeansProjects\\MP3Player\\src\\MP3PlayerPackage\\loop_hover1.png"));
   
    }//GEN-LAST:event_loopBtnMouseExited

    private void stopBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stopBtnMouseClicked
        co.stop();
    }//GEN-LAST:event_stopBtnMouseClicked

    private void playBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playBtnMouseClicked
        co.resume();
    }//GEN-LAST:event_playBtnMouseClicked

    private void openBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openBtnMouseClicked
        // TODO add your handling code here:
       FileFilter filter=new FileNameExtensionFilter("MP3 Files","mp3","mpeg3");
       JFileChooser chooser=new JFileChooser("C:\\Users\\abdelkarim\\Desktop\\My pictures\\sounds");
       int returnVal=chooser.showOpenDialog(null);
       
        if (returnVal==JFileChooser.APPROVE_OPTION) {
            co.stop();
            File myfile=chooser.getSelectedFile();
            String song=myfile+"";
            
            String name=chooser.getSelectedFile().getName();
            songTitleR.setText(name);
      
            co.play(song);
            
        }
    }//GEN-LAST:event_openBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MP3PlayerGUII.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MP3PlayerGUII.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MP3PlayerGUII.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MP3PlayerGUII.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MP3PlayerGUII().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel closeBtn;
    private javax.swing.JLabel dragBar;
    private javax.swing.JLabel loopBtn;
    private javax.swing.JLabel minBtn;
    private javax.swing.JLabel openBtn;
    private javax.swing.JLabel pauseBtn;
    private javax.swing.JLabel playBtn;
    private javax.swing.JLabel songTitle;
    public static javax.swing.JLabel songTitleR;
    private javax.swing.JLabel stopBtn;
    // End of variables declaration//GEN-END:variables

}
